name: "Deploy"

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Deploy Production
              if: github.ref == 'refs/heads/main'
              run: |
                  export NODE_ENV="production"
                  export PUBLIC_URL="https://cod-ed.github.io/handwrite-web"
                  git config --global user.email "yashlamba2000@gmail.com"
                  git config --global user.name "yashlamba"
                  git remote set-url origin https://yashlamba:${{secrets.TOKEN}}@github.com/cod-ed/handwrite-web
                  npm install
                  npm run deploy

            - name: Deploy Development
              if: github.ref == 'refs/heads/dev'
              run: |
                  export NODE_ENV="development"
                  export PUBLIC_URL="https://cod-ed.github.io/handwrite-web/dev"
                  git config --global user.email "yashlamba2000@gmail.com"
                  git config --global user.name "yashlamba"
                  git remote set-url origin https://yashlamba:${{secrets.TOKEN}}@github.com/cod-ed/handwrite-web
                  npm install
                  npm run deploydev
