name: "Deploy"

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Deploy Production
              if: github.ref == 'refs/heads/main'
              run: |
                  git config user.name "GitHub Action" && git config user.email "github-action@github.com"
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm install
                  npm run deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_ENV: "production"
                  PUBLIC_URL: "https://cod-ed.github.io/handwrite-web"

            - name: Deploy Development
              if: github.ref == 'refs/heads/dev'
              run: |
                  git config user.name "GitHub Action" && git config user.email "github-action@github.com"
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm install
                  npm run predeploy
                  npm run deploydev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_ENV: "production"
                  PUBLIC_URL: "https://cod-ed.github.io/handwrite-web/dev"
